Update mainnet-validator-setup.md
persistenceOne/persistence-docs pull request #19
Opened 2022-12-29 00:10 UTC by napelvs

I've combined my variant of creating a validator, with the existing one created by the Persistence team.

2023-01-04 10:37 UTC, ajeet97 requested changes

2023-01-04 10:37 UTC, ajeet97 commented on build/validators/mainnet-validator-setup.md
> +	--gas-prices="10uxprt"
update the gas price to `0.025uxprt`

2023-01-04 15:44 UTC, napelvs commented on build/validators/mainnet-validator-setup.md
> +	--gas-prices="10uxprt"
Done!

2023-01-05 06:32 UTC, ajeet97 approved these changes
LGTM

2023-01-05 09:10 UTC, merged